### PR TITLE
Nemwel blog milestone 7 : Add devise

### PR DESCRIPTION
**Pull request by Nemwel-Boniface**
## Hello reviewer(s)
In this milestone I was able to:

- [x] Remove current_user method in ApplicationController
- [x] Install and setup devise
- [x] Implement Sign in, Sign up, logout 
- [x] Modify wireframes to match the provided wireframes
- [x] Check and fix all found offenses

Below I will include the views : 

**Sign in**

image

**Sign up**

image

**Edit user details which only works when you sign in**

image

**List all users that only shows when you signin**

image

Incase you face any challenge creating the db run the following:

`rake db:drop`
`rake db:create`
`rake db:schema:load`
`rake db:migrate` 

Thank you for taking the time to review my project :pray:

### CODE REVIEW

**Review by ShadyShawkat — CHANGES_REQUESTED** [review]
## Hi @Nemwel-Boniface, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

Image

## Required Changes ♻️
- [ ] Kindly make sure that the migrations run successfully so that I can access your project. Currently, when I run the migrations I get the following error which prevents me from running the project.
image
- To recreate this error, you first need to drop your database and then create it again. After that, when you run the migrations you'll get the error.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Nemwel-Boniface** [comment]
Hello @ShadyShawkat . I had notified the reviewer(s) of the process to take in case they have trouble running migrations. In your comment, I have not seen your comment on whether you had tried it and it did not work so I know that there is an issue. I have tried it with another partner's machine and it works. Kindly recheck it.

**Comment by Nemwel-Boniface** [comment]
On request from the previous reviewer, I will drop my database, run the steps that I have included in my pull request description and try to create a new User. 

It also seems like there is an issue when someone using a windows OS tries to clone and test my project. I am currently running on Ubuntu and I have tested it also from my partner who uses Ubuntu as well and it works.

Below I will include screenshots of it working locally on my machine.

**Drop the DB and re-create it**

image

**Try to create a user**

image

**Review by ShadyShawkat — APPROVED** [review]
## Hi @Nemwel-Boniface, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 
- Your readme looks professional ✔️ 
- Good overall design ✔️ 
- Your code is clean and well documented ✔️

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
